name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Setup Java
        uses: actions/checkout@v4
        with:
          distribution: 'termurin'
          java-version: '21'

      - name: Build Jar
        run: |
          chmod +X ./mvnw
          ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOCKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest .

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER}}
          key: ${{ secrets.EC2_SSH_KEY}}
          script:
            docker stop spring-demo || true
            docker rm spring-demo || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest
            docker run -d --name spring-demo -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest
